server:
  port: 80
  error:
    include-message: always
spring:
  application:
    name: organization-service
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error
