server:
  port: 80
  error:
    include-message: always
spring:
  application:
    name: organization-service
  datasource:
    url: jdbc:h2:mem:dborganization
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error
